apiVersion: v1
kind: Service
metadata:
  name: b2bservice
  namespace: b2bdev
spec:
  selector:
    app: b2b-dev
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 5000